---
title: "cat wrangling"
author: "Catherine Takata"
date: "2/24/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnaturalearth)
library(here)
library(sf)
library(janitor)
library(tmap)
library(leaflet)
```

```{r}
foraging <- read.csv(here("data","2018_foraging.csv")) %>% 
  clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  rename(aerial_survey_yr = year)
```


```{r summary stats, echo = F}
dive_data <- foraging %>% 
  select(otter_lat_deg, otter_long_deg, suc) %>% 
  drop_na() %>% 
  mutate(suc = case_when(
    suc %in% "Y" ~ "Successful dive",
    suc %in% "N" ~ "Unsuccessful dive",
    suc %in% "T" ~ "Travel dive",
    suc %in% "C" ~ "Previous dive",
    suc %in% "I" ~ "Interactive otter dive",
    suc %in% "U" ~ "Unknown"
    ))
```

```{r}
dive_locations <- st_as_sf(x = dive_data, 
                        coords = c("otter_long_deg", "otter_lat_deg"),
                        crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
#mapview(dive_locations)
```

```{r}
alaska <- read_sf(here("data", "alaska_shape", "tl_2017_02_place.shp")) %>% 
  select(NAME, ALAND) %>% 
  rename(county_name = NAME, land_area = ALAND)
```


```{r}
tmap_mode(mode = "view")

tm_shape(alaska) +
  tm_fill("land_area") +
  tm_shape(dive_locations) + 
  tm_symbols()

#tm_shape(alaska) + 
  #tm_dots(dive_locations) +
  #tm_basemap("OpenStreetMap")
```



# Leaflet 
```{r}
basemap = leaflet(plot_map) %>% 
  addTiles() %>% 
  addLayersControl(
    position = "bottomright",
    overlayGroups = c("2019-COVID (new)", "2019-COVID (cumulative)", "2003-SARS", "2009-H1N1 (swine flu)", "2014-Ebola"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  hideGroup(c("2019-COVID (cumulative)", "2003-SARS", "2009-H1N1 (swine flu)", "2014-Ebola")) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  fitBounds(~-100,-60,~60,70) %>%
  addLegend("bottomright", pal = cv_pal, values = ~cv_large_countries$deaths_per_million,
            title = "<small>Deaths per million</small>") 
```

