---
title: "otters wrangling"
author: "lor + cat"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(kableExtra)
library(broom)
```

```{r}
# reading in data + some cleaning up 
otters <- read.csv(here("data", "2018_Foraging.csv")) %>% 
  clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  rename(aerial_survey_yr = year) # i know you probably hate this name LOL but i only renamed it because this is a DIFFERENT THING than the date; i was getting confused as to why the date and year columns had diff years listed so i just want to make that clear
```

```{r}
# WIDGET 2 STUFF

# to create a histogram of counts of prey obtained we would just need the prey item, success of dive (which indicates if dive is brought to surface or not), and prey quantity to determine the number of prey successfully caught 
prey_2 <- otters %>% 
  select(suc, prey_item, date, age, prey_qty) %>% 
  group_by(prey_item) %>% 
  count(suc, wt = prey_qty) %>% 
  rename(prey_caught = n) %>% 
  filter(suc == "Y") 

# example plot with all a couple prey shown: widget selection would be CLA, SAG, UNK
top_prey <- prey %>% 
  filter(prey_item == "CLA" |
           prey_item == "SAG" |
           prey_item == "UNK")

ggplot(data = top_prey, aes(x = prey_item, y = prey_caught)) +
  geom_col()
```


```{r}
age_sex <- otters %>% 
  filter(sex == "F" | sex == "M") %>% 
  filter(age == "J" | age == "A")

otter_stats <- age_sex %>% 
  group_by(sex, age) %>% 
  summarise(dive_time = round(mean(dt, na.rm = TRUE),2),
            prey_quantity = round(mean(prey_qty, na.rm = TRUE), 2) 
            )

otter_stats %>% 
   kable(col.names = c("Sex", "Age", "Mean Dive Time (seconds)", "Mean Prey Quantity")) %>% 
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
  
```

```{r}
# Messing with regression
otters_suc <- otters %>% 
  filter(age == "J" | age == "A") %>% 
  filter(suc %in% c("Y", "N")) %>% 
  mutate(suc = fct_drop(suc))

levels(otters_suc$suc) # [1] "N" "Y"

otters_blr <- glm(suc ~ sky + age, 
                  data = otters_suc, 
                  family = "binomial")

otters_blr
summary(otters_blr)

blr_fitted <- otters_blr %>% 
  broom::augment(type.predict = "response")
```

```{r}
ggplot(data = blr_fitted, aes(x = dt, y = .fitted)) +
  geom_point(aes(color = age)) +
  geom_smooth(aes(color = age), se = FALSE) +
  labs(x = "dive time",
       y = "Probability of a successful dive")
```

```{r}
otters_lm <- lm(prey_qty ~ dt, data = otters)

summary(otters)

otters_lm_tidy <- broom::tidy(otters_lm)

# plot
ggplot(data = otters, aes(x = prey_qty, y = dt)) +
  geom_jitter(size = 2) +
  geom_smooth(method = "lm",
              color = "red",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) + # geom_smooth is to add a linear model to a scatterplot
  labs(x = "Prey quantity", y = "Dive time (seconds)") +
  theme_light() +
    ggpubr::stat_regline_equation(label.x = 17, label.y = 300)
```



```{r}
# logistic regression: what is the probability of a dive being successful, based on otter age and sex?
# independent variable: categorical (age, sex)
# dependent variable: dichotomous (yes = 1, no = 0)

blr_subset <- age_sex %>% 
  filter(suc == "Y" |
         suc == "N") %>% 
  mutate(suc = fct_drop(suc))

blr_subset$suc <- as.factor(blr_subset$suc)

levels(blr_subset$suc) # N = 0, Y = 1. so Y is our reference level; we will be looking at probability of a successful dive

success_blr <- glm(suc ~ age + sex,
                   data = blr_subset,
                   family = "binomial")

age_blr <- glm(suc ~ age,
                   data = blr_subset,
                   family = "binomial")

summary(age_blr)

summary(success_blr)
# Reference levels are adult and female (bc they don't show up in the model)
# Based on the p-value, sex is significantly non zero (??)
# Compared to a reference level of "adult", if an otter is a "juvenile", it is more likely to have a successful dive
# Compared to a reference level of "female", if an otter is a "male", it is less likely to have a successful dive

ggplot(data = blr_subset, aes(x = suc, y = age)) +
  geom_jitter() 

ggplot(data = blr_subset, aes(x = suc, y = sex)) +
  geom_jitter()

blr_fitted <- success_blr %>% 
  broom::augment(type.predict = "response")


sex_plot <- ggplot(data = blr_fitted, aes(x = sex, y = .fitted)) +
  geom_col() +
  labs(x = "Sex",
       y = "Probability of outcome successful")

age_plot <- ggplot(data = blr_fitted, aes(x = age, y = .fitted)) +
  geom_col() +
  labs(x = "Age",
       y = "Probability of outcome successful")


blr_tidy <- broom::tidy(success_blr)

blr_tidy$p.value <- round(blr_tidy$p.value, digit = 3)

blr_tidy %>% 
  mutate(p.value = case_when(p.value < 0.0001 ~ "< 0.0001",
                             TRUE ~ as.character(p.value))) %>% 
  kable(col.names = c("Term", "Estimate", "Standard Error", "Statistic", "P-value")) %>% 
  kable_styling(full_width = FALSE,
                bootstrap_options = "striped")

```





